### ISSUE TITLE
Winning

### ISSUE THREAD

**Issue by Zach-Kauffman** [cs361w2019-osu/sprint1-project-group-3#4]
As a player, I want to win after I have sunk all of my opponent's ships

Time estimate: 2 hours

**Comment by strozzi1** [comment]
This is doable! I think we this can be done in Board.java within public Result attack(int x, char y)

May need help, but all we gotta do is add a check for if the current attack has hit and if so add it to like some sort of counter of hits and if we've hit X hits out of X hits, then set result to surrender!

**Comment by dakota-osu** [comment]
Closed during another user story
